plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.yourteam.autho'
    compileSdk 36

    defaultConfig {
        applicationId "com.yourteam.autho"
        minSdk 30
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    // Core UI
    implementation 'androidx.activity:activity:1.9.0'
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material

    // Firebase
    implementation libs.firebase.firestore

    // Biometric
    implementation 'androidx.biometric:biometric:1.1.0'

    // Room
    implementation 'androidx.room:room-runtime:2.6.0'
    annotationProcessor 'androidx.room:room-compiler:2.6.0'

    // Encrypted SharedPreferences
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'

    // Tests
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}